language: node_js
node_js:
- '8'
sudo: enabled
addons:
  ssh_known_hosts: 47.52.171.181
  sauce_connect: true
  apt:
    update: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
after_deploy:
- ssh -tt root@47.52.171.181 < ./script/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_b7b04a5a5e64_key -iv $encrypted_b7b04a5a5e64_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
