language: node_js
node_js:
- '8'
sudo: enabled
addons:
  ssh_known_hosts: 47.52.171.181
  sauce_connect: true
  apt:
    update: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
after_deploy:
- ssh -tt root@47.52.171.181 < ./script/deploy.sh
before_install:
- chmod 600 ~/.ssh/id_rsa